apiVersion: v1
kind: Namespace
metadata:
  name: "2401063"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-finder-deployment
  namespace: "2401063"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-finder
  template:
    metadata:
      labels:
        app: recipe-finder
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: recipe-finder
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401063/recipe-finder:v1
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_KEY
          value: "cc61bff714d14ffe98913e198a562acf"
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-finder-service
  namespace: "2401063"
spec:
  selector:
    app: recipe-finder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
