apiVersion: v1
kind: Service
metadata:
  name: recipe-finder-service
  namespace: "find_my_recipe"
spec:
  selector:
    app: recipe-finder
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
